### ISSUE TITLE
mqtt/config POST to set own local broker fails (no topics)

### ISSUE THREAD

**Issue by AnMiPe** [scrool/xled-docs#1]
Hi! Thanks for documenting the twinkly private api!
I managed to change the mqtt config settings to my own local broker, but after that I cannot see any of my twinkly topics on my broker? I tried to send the authentication with user: and password: in the json. The response was OK and code 1000. 

Thank you! 
Andre

**Comment by scrool** [comment]
Hey! I'm wondering what have you used to to look for Twinkly's topics? I didn't know there is a way to publish available topics.

Regarding authentication - I don't think you should use user nor password in the json.

**Comment by AnMiPe** [comment]
Thanks for your reply! I subscribed to the universal topic # on my broker. My Broker needs authentication, but you think I cannot change it? User was changed successfully, but I don't think the password did...

**Comment by scrool** [comment]
AFAIK by default Twinkly doesn't use any authentication to connect to the broker.
