### ISSUE TITLE
RT multi-frame info seems to be wrong for a 600 string

### ISSUE THREAD

**Issue by JLOrwell** [scrool/xled-docs#30]
I have a gen-2 string that has 600 lights.  It is a split string with two 300-strings.
I attempted to use the format shown for more than 300 lights but that didn't work.  
Half of the lights were lit and i noticed that the first light on the half that was lit was out.  Additionally they were all the wrong color.
I used the old-style frame with 10-byte header and half of the lights lit up, including the first light.  After much trial and error i was able to determine that i can send a single frame with a 10-byte header and up to 472x3 bytes and successfully control that many bulbs.  Again, a single frame.  I am unable to determine how the second frame is sent.  I have attempted to use wireshark to do so but it's not capturing anything to the strings.  It may be because my computer is using a wired connection.  Not sure.
Anyhow, this seems to indicate yet another frame setup besides the two known ones.

**Comment by scrool** [comment]
Could you provide following info in a [code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks):

* Navigate to http://HOSTNAME/xled/v1/gestalt and pretty format output you get. Use e.g. http://jsonprettyprint.net/ . You can anonymize following fields: `hw_id`, `mac`, `uuid` by replacing some of the values, e.g. by "X"s . ​
* Navigate to http://HOSTNAME/xled/v1/fw/version and pretty format output you get. Use e.g. http://jsonprettyprint.net/ . 


> Half of the lights were lit and i noticed that the first light on the half that was lit was out.

Please check out LED configuration: https://xled-docs.readthedocs.io/en/latest/rest_api.html#get-led-config and corresponding https://xled-docs.rePaste output in adthedocs.io/en/latest/rest_api.html#set-led-config . This way you could (artificially) limit amount of LED that the device has available. From what I can tell, this is how one could set in app that they have connected an extension (yes, I understand that it is not possible to split yours).

> I used the old-style frame

By old-style do you mean [Version 2](https://xled-docs.readthedocs.io/en/latest/protocol_details.html#version-2)?

**Comment by JLOrwell** [comment]
Yes version è.  Now I have it working now.  The data I saw seemed to
indicate that byte 1 was the total number of packets, so I was sending 2.
Someone else helpfully corrected this and told me it has to be 3
