### ISSUE TITLE
Download firmware?

### ISSUE THREAD

**Issue by ikrowni** [scrool/xled-docs#4]
Hello I'm interested in your project. Is there anyway to get the firmware from the device to be uploaded on my own esp32 board?

I don't really have the funds to drop hundreds for a few LEDs. But I would love to upload the firmware to my own esp32 then hook that to my own choice of LEDs and still be able to use the app to control them.

Thanks for any help with this. I just posted this github to home assistant forums where someone else is currently attempting to integrate control of trinkly lights for local control as well.

**Comment by scrool** [comment]
I'm afraid I can't help you with firmware. The documentation covers few Twinkly models and doesn't go much of beyond interaction with them. Downloadable firmware is out of its scope.
