### ISSUE TITLE
Firmware Version 2.5.9 HowTo use MQTT

### ISSUE THREAD

**Issue by testit2020** [scrool/xled-docs#5]
Hi,
I just use xled-docs-api-reference. There ist described howto change MQTT-data. But I don't get data on my own MQTT-Server. Do you have hint,, how to use?
I use it with:

broker_host: 192.168.178.89 ,broker_port: 1885
client_id: (mac-number) , user: twinkly32 (was default)

Where can I get the Password? Or how should it set?
Thank you.

**Comment by scrool** [comment]
I haven't adapted documentation for almost any API nor behavior for Generation II. I'm not sure what has changed yet so I'll have to look into that later.

**Comment by scrool** [comment]
Apparently Gen II hardware uses TLS to connect to MQTT. I'm not sure if a certificate is validated or even pinned in the firmware though.

**Comment by testit2020** [comment]
SO thank you for your time, Merry Christmas.

**Comment by wilcooo** [comment]
> I'm not sure if a certificate is validated or even pinned in the firmware though.

The certificate is validated. When trying to connect to a self-hosted secure broker it fails with "unknown_ca".

**Comment by scrool** [comment]
> The certificate is validated. When trying to connect to a self-hosted secure broker it fails with "unknown_ca".

Yep. Most likely pinned.
