### ISSUE TITLE
new fields/values in gestalt with latest firmware

### ISSUE THREAD

**Issue by MarkAlanJones** [scrool/xled-docs#6]
My Gestalt  results with latest fw (2.5.9) shows some new fields and values

this is a new 400 LED "Cluster" model - version II

`{
    "product_name": "Twinkly",
    "hardware_version": "100",
    "bytes_per_led": 3,
    "hw_id": "71cbe8",
    "flash_size": 64,
    "led_type": 14,
    "product_code": "TWC400STP",
    "fw_family": "F",
    "device_name": "Twinkly_71CBE9",
    "uptime": "2484468",
    "mac": "98:f4:ab:71:cb:e9",
    "uuid": "C668EFCC-E290-4297-9324-5F34C7FC1DE0",
    "max_supported_led": 1200,
    "number_of_led": 400,
    "led_profile": "RGB",
    "frame_rate": 13,
    "measured_frame_rate": 14.29,
    "movie_capacity": 992,
    "wire_type": 1,
    "copyright": "LEDWORKS 2018",
    "code": 1000
}`

The following are no longer included - product_version, led_version, rssi, base_leds_number

also note - new fw_family "F", hw_id is slightly different than device_name/mac
wire_type ? 
Copyright moved to 2018 (rather than 2020 !)

Thanks for documenting this API - great work !

**Comment by MarkAlanJones** [comment]
Also note that code = 1000 is "success" 

the wiki says 1100 but shows 1000 in the examples

**Comment by MarkAlanJones** [comment]
uptime is milliseconds since start (e.g. divide by 1000 for seconds since start)

**Comment by magicus** [comment]
Interesting. I got (after a firmware upgrade to 2.5.9):
`{'product_name': 'Twinkly', 'hardware_version': '100', 'bytes_per_led': 4, 'hw_id': '****f4', 'flash_size': 64, 'led_type': 12, 'product_code': 'TWW210SPP', 'fw_family': 'G', 'device_name': 'Twinkly_387DF5', 'uptime': '18386946', 'mac': '98:f4:ab:**:**:f5', 'uuid': '0A1E721B-AE33-****-****-D72A22D76425', 'max_supported_led': 1200, 'number_of_led': 210, 'led_profile': 'RGBW', 'frame_rate': 11, 'measured_frame_rate': 12.82, 'movie_capacity': 992, 'wire_type': 4, 'copyright': 'LEDWORKS 2018', 'code': 1000}`

It is worth noting that the hw_id corresponds to the **actual** last three bytes of the MAC address, in contrast with the value returned in the "mac" field, which is 1 too high. 

Also worth noting is that my `fw_family` is `G`. But the copyright is still in 2018...

**Comment by scrool** [comment]
I plan to update this as I upgrade my lights. Stay tuned.

**Comment by githubprince** [comment]
Same here with HW ID and MAC, but firmware family is reported as "M" on the same FW version {"version":"2.5.9","code":1000}:{"product_name":"Twinkly","hardware_version":"100","bytes_per_led":3,"hw_id":"37e9f0","flash_size":64,"led_type":19,"product_code":"TWS600STP","fw_family":"M","device_name":"Twinkly_37E9F1","uptime":"1450298","mac":"98:f4:ab:37:e9:f1","uuid":"********-****-****-****-************","max_supported_led":1200,"number_of_led":600,"led_profile":"RGB","frame_rate":9,"measured_frame_rate":10.1,"movie_capacity":992,"wire_type":1,"copyright":"LEDWORKS 2018","code":1000}

**Comment by scrool** [comment]
I have updated documentation with `fw_family` "F" and data that it present in couple of commits back.
