### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by matejdro** [scrool/xled-docs#7]
It seems like later models of Twinkly lights have an ability to set looping playlists of effects.

1. Before movie is uploaded (before `/movies/full` call), `POST /xled/v1/movies/new` is called with some metadata for the movie, notably with the `unique_id` that is later used for the playlist:

```json
{
  "descriptor_type": "aww_raw",
  "fps": 15,
  "frames_number": 212,
  "leds_per_frame": 250,
  "name": "Waves",
  "unique_id": "4e2bf906-49a4-49e2-a77b-d0c3cf802beb"
}
```

Multiple pairs of `/movies/new` and `/movies/full` are called to upload multiple effects onto Twinkly

2. `POST /xled/v1/playlist` call is made with a sequence of previously uploaded movies:

```
{
  "entries": [
    {
      "duration": 10,
      "unique_id": "C5FE2809-8EC4-48F7-98CC-C6EA4D1D1871"
    },
    {
      "duration": 10,
      "unique_id": "D835078B-C48E-4647-AC5A-22E4E444928A"
    },
    {
      "duration": 10,
      "unique_id": "E9030A6A-F320-466E-971D-0042B1BA7BDE"
    }
  ]
}
```

duration is in seconds.

3. Playlist can be started by putting lights into `playlist` mode via `POST /xled/v1/led/mode`:

```json
{"mode":"playlist"}
```

I have `TWS250GOP` model running 2.5.9 firmware.

**Comment by magicus** [comment]
Is the `descriptor_type` always `aww_raw`?

**Comment by magicus** [comment]
To sort of answer myself, in https://github.com/scrool/xled/issues/51 there's this contrubition from another user: 

```
POST /xled/v1/movies/new
{"descriptor_type":"rgbw_raw","fps":30,"frames_number":2,"leds_per_frame":250,"name":"Red","unique_id":"1b93643d-716f-4f1c-a81a-45a9bb12d6e0"}

POST /xled/v1/movies/full
2000 bytes of data (2 pages of 250 lights 4 byte per light)

POST /xled/v1/led/mode 
{"mode":"movie","shop_mode":0}
```

in which `descriptor_type` is `rgbw_raw`.

And we also notice that there is a new attribute `shop_mode` to `led/mode`.

**Comment by matejdro** [comment]
I only have one twinkly (aww one) so I could not confirm. Great that you have other sources too.

**Comment by magicus** [comment]
Oh, I see, AWW is a Twinkly format ([product link](https://www.twinkly.com/gold-edition/)). Interesting. How is this encoded? What is the output of get_device_info on an AWW device?

**Comment by magicus** [comment]
There are more commands associated with the playlist functionality:

Calling `/xled/v1/movies` returns something like this:

```
{
  "movies": [
    {
      "id": 0,
      "name": "Love",
      "unique_id": "941862FB-844C-4E29-AB68-EE64D626695D",
      "descriptor_type": "rgbw_raw",
      "leds_per_frame": 210,
      "frames_number": 4,
      "fps": 0
    }
  ],
  "available_frames": 986,
  "max_capacity": 992,
  "code": 1000
}
```

**Comment by matejdro** [comment]
> What is the output of get_device_info on an AWW device?

You mean the gestalt endpoint?

```json
{
    "product_name": "Twinkly",
    "hardware_version": "100",
    "bytes_per_led": 3,
    "hw_id": "e7ae58",
    "flash_size": 64,
    "led_type": 11,
    "product_code": "TWS250GOP",
    "fw_family": "F",
    "device_name": "Twinkly_E7AE59",
    "uptime": "690293411",
    "mac": "ac:67:b2:e7:XX:XX",
    "uuid": "EF47D13E-5256-4929-8017-XXXXXXXXXXXX",
    "max_supported_led": 1200,
    "number_of_led": 250,
    "led_profile": "AWW",
    "frame_rate": 20,
    "measured_frame_rate": 25.64,
    "movie_capacity": 992,
    "wire_type": 1,
    "copyright": "LEDWORKS 2018",
    "code": 1000
}
```
From your link, I think AWW stands for `Amber, Warm White, Cold White`, so it is the color variant.

**Comment by magicus** [comment]
@matejdro Thanks! Is the AWW format represented by three bytes? So if you send a movie frame with a repeating pattern of `0xff 0x00 0x00` you will get all LEDs fully amber, and with `0x00 0xff 0x00` you will get full warm white and `0x00 0x00 0xff` full cold white?

**Comment by matejdro** [comment]
> Thanks! Is the AWW format represented by three bytes? So if you send a movie frame with a repeating pattern of 0xff 0x00 0x00 you will get all LEDs fully amber, and with 0x00 0xff 0x00 you will get full warm white and 0x00 0x00 0xff full cold white?

I've played with this a bit and this is exactly how it seems to work.

**Comment by magicus** [comment]
@matejdro Thanks! Did I guess the order correct as well? Amber, warm white, cold white?

**Comment by matejdro** [comment]
Yup
